import type { D1Migration } from "@cloudflare/vitest-pool-workers";

declare module "cloudflare:test" {
	// `Env` is generated by `wrangler types` into worker-configuration.d.ts.
	interface ProvidedEnv extends Env {
		TEST_MIGRATIONS: D1Migration[];
	}
}
